on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.34.8/install
      - uses: cachix/cachix-action@v17
        with:
          name: devenv
      - run: nix profile add nixpkgs#devenv
      - run: devenv test --override-dotfile
