on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get tag name
        id: tag
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Check if prerelease
        id: prerelease
        run: |
          TAG="${{ steps.tag.outputs.tag_name }}"
          if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-.+ ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          release_name: Release ${{ steps.tag.outputs.tag_name }}
          draft: false
          prerelease: ${{ steps.prerelease.outputs.is_prerelease }}

  build:
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - x86_64-linux
          - aarch64-linux
          - x86_64-darwin
          - aarch64-darwin
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - run: nix profile add nixpkgs#devenv
      - name: Build for ${{ matrix.platform }}
        run: |
          devenv build outputs.default.${{ matrix.platform }} \
            | tee kustomize-plugins-${{ matrix.platform }}.pth
      - name: Create tarball
        run: |
          tar --directory=$(cat kustomize-plugins-${{ matrix.platform }}.pth) \
            -cf kustomize-plugins-${{ matrix.platform }}.tar.gz .
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./kustomize-plugins-${{ matrix.platform }}.tar.gz
          asset_name: kustomize-plugins-${{ matrix.platform }}.tar.gz
          asset_content_type: application/gzip
