on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - x86_64-linux
          - aarch64-linux
          - x86_64-darwin
          - aarch64-darwin
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - run: nix profile add nixpkgs#devenv
      - name: Build for ${{ matrix.platform }}
        run: |
          devenv build outputs.default.${{ matrix.platform }} \
            | tee kustomize-plugins-${{ matrix.platform }}.pth
      - name: Create tarball
        run: |
          tar --directory=$(cat kustomize-plugins-${{ matrix.platform }}.pth) \
            -cf kustomize-plugins-${{ matrix.platform }}.tar.gz .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kustomize-plugins-${{ matrix.platform }}
          path: kustomize-plugins-${{ matrix.platform }}.tar.gz

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: tag
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Check if prerelease
        id: prerelease
        run: |
          TAG="${{ steps.tag.outputs.tag_name }}"
          if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-.+ ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Flatten artifacts
        run: |
          mkdir -p release-assets
          find artifacts -name "*.tar.gz" -exec cp {} release-assets/ \;
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          draft: false
          prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
          files: release-assets/*.tar.gz
